services:
  - type: web
    name: 2ie-bibliotheque-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: 2ie-bibliotheque-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: 2ie-bibliotheque-db
    databaseName: 2ie_bibliotheque
    user: 2ie_user
    plan: free 